[versions]
springboot = "3.0.4"
springcloud = "2022.0.0"
springcloudalibaba = "2022.0.0.0-RC1"
springcloudstarter = "4.0.0"
management="1.1.0"

[libraries]
spring-cloud-starter-alibaba-nacos-config={ module = "com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config", version.ref = "springcloudalibaba" }
spring-cloud-starter-alibaba-nacos-discovery={ module = "com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery", version.ref = "springcloudalibaba" }
spring-cloud-starter-gateway={ module = "org.springframework.cloud:spring-cloud-starter-gateway", version.ref = "springcloudstarter" }
spring-cloud-starter-loadbalancer={ module = "org.springframework.cloud:spring-cloud-starter-loadbalancer", version.ref = "springcloudstarter" }
spring-cloud-starter-bootstrap={ module = "org.springframework.cloud:spring-cloud-starter-bootstrap", version.ref = "springcloudstarter" }
spring-boot-starter-web={ module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springboot" }

[plugins]
dependencymanagement = { id = "io.spring.dependency-management", version.ref = "management" }
springframeworkboot = { id = "org.springframework.boot", version.ref = "springboot" }
